// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"GabeMZ_FogEffects","status":true,"description":"[v2.1.0] Allows to create and display fog effects on maps and battles.","parameters":{"fogSettings":"[\"{\\\"fogFilename\\\":\\\"Fog\\\",\\\"fogOpacity\\\":\\\"150\\\",\\\"fogBlendMode\\\":\\\"2\\\",\\\"fogMoveX\\\":\\\"0.4\\\",\\\"fogMoveY\\\":\\\"-0.2\\\"}\"]","fogInMap":"true","fogInBattle":"false","fogOptionsMenuCommand":"===============================================","commandEnabled":"true","commandName":"Fog Effects"}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}}
];
